gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  ports:
    - '10800:80'
  volumes:
    - 'gitlab-config:/etc/gitlab'
    - 'gitlab-logs:/var/log/gitlab'
    - 'gitlab-data:/var/opt/gitlab'