phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - MYSQL_ROOT_PASSWORD=password
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions