version: '2'
services:
  openvpn-rancherlocal-server:
    privileged: true
    image: mdns/rancher-openvpn:1.1
    environment:
      AUTH_METHOD: rancherlocal
      AUTH_RANCHERLOCAL_URL: http://private-ip-of-ranche-server:8080/v1/token
      CERT_CITY: Venice
      CERT_COUNTRY: US
      CERT_EMAIL: polinchw@gmail.com
      CERT_ORG: BPE
      CERT_OU: IT
      CERT_PROVINCE: FL
      OPENVPN_EXTRACONF: ''
      REMOTE_IP: public-ip-of-open-ssh-server
      REMOTE_PORT: '1194'
      VPNPOOL_CIDR: '16'
      VPNPOOL_NETWORK: 10.43.0.0
    volumes_from:
    - openvpn-rancherlocal-data
    ports:
    - 1194:1194/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: openvpn-rancherlocal-data
  openvpn-rancherlocal-data:
    image: busybox
    entrypoint:
    - /bin/true
    volumes:
    - /etc/openvpn/
    labels:
      io.rancher.container.start_once: 'true'
