logspout:
  restart: always
  environment:
    ROUTE_URIS: 'logstash://logstash:5000'
  volumes:
  - '/var/run/docker.sock:/var/run/docker.sock'
  external_links:
  - logstash/logstash-collector:logstash
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_ne: app=es,app=logstash,app=kibana
  tty: true
  image: rancher/logspout-logstash:v0.2.0
  stdin_open: true
