apiVersion: v1
kind: Service
metadata:
  annotations:
    io.rancher.container.hostname_override: container_name
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins-primary
  name: jenkins-primary
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: jenkins-primary
status:
  loadBalancer: {}
