apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    io.rancher.container.hostname_override: container_name
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins-primary
  name: jenkins-primary
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jenkins-primary
    spec:
      containers:
      - image: polinchw/jenkins:2.103
        name: jenkins-primary
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: jenkins-primary-claim0
        - mountPath: /usr/bin/docker
          name: jenkins-primary-claim1
        - mountPath: /var/jenkins-home
          name: jenkins-home
      restartPolicy: Always
      volumes:
      - name: jenkins-primary-claim0
        persistentVolumeClaim:
          claimName: jenkins-primary-claim0
      - name: jenkins-primary-claim1
        persistentVolumeClaim:
          claimName: jenkins-primary-claim1
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-home
status: {}
